{% set version = "2.40-1" %}

package:
  name: r-survival
  version: {{ version.replace("-", "_") }}

source:
  fn: survival_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/survival_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/survival/survival_{{ version }}.tar.gz
  sha256: 91d5217847e39bebcbce4f0a2e295304e5816b1270e71f5f2ed39807f004ee82

build:
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - r-base
    - posix                # [win]
    - m2w64-toolchain      # [win]
    - r-matrix
  run:
    - r-base
    - r-matrix
    - m2w64-gcc-libs       # [win]

test:
  commands:
    - R -e "library('survival')"    # [not win]
    - R -e \"library('survival')\"  # [win]

about:
  home: https://github.com/therneau/survival
  license: LGPL-2.0
  summary: 'Contains the core survival analysis routines, including definition of Surv objects,  Kaplan-Meier
    and Aalen-Johansen (multi-state) curves, Cox models, and parametric accelerated
    failure time models.'

extra:
  recipe-maintainers:
    - ocefpaf
