{% set version = '2.42-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survival
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survival_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survival/survival_{{ version }}.tar.gz
  sha256: e33c44ee95961ff3c1bd1afe040d3059c143a72387d8e47fdbeba61c9d605daf

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-matrix

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('survival')"           # [not win]
    - "\"%R%\" -e \"library('survival')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/therneau/survival
  license: LGPL (>= 2)
  summary: Contains the core survival analysis routines, including definition of Surv objects,  Kaplan-Meier
    and Aalen-Johansen (multi-state) curves, Cox models, and parametric accelerated
    failure time models.
  license_family: LGPL

extra:
  recipe-maintainers:
    - ocefpaf
    - mingwandroid

# The original CRAN metadata for this package was:

# Title: Survival Analysis
# Maintainer: Terry M Therneau <therneau.terry@mayo.edu>
# Priority: recommended
# Package: survival
# Version: 2.42-6
# Depends: R (>= 2.13.0)
# Imports: graphics, Matrix, methods, splines, stats, utils
# LazyData: Yes
# LazyLoad: Yes
# ByteCompile: Yes
# Authors@R: c(person(c("Terry", "M"), "Therneau", email="therneau.terry@mayo.edu", role=c("aut", "cre")), person("Thomas", "Lumley", role=c("ctb", "trl"), comment="original S->R port and R maintainer until 2009"))
# Description: Contains the core survival analysis routines, including definition of Surv objects,  Kaplan-Meier and Aalen-Johansen (multi-state) curves, Cox models, and parametric accelerated failure time models.
# License: LGPL (>= 2)
# URL: https://github.com/therneau/survival
# NeedsCompilation: yes
# Packaged: 2018-07-12 12:21:01 UTC; therneau
# Author: Terry M Therneau [aut, cre], Thomas Lumley [ctb, trl] (original S->R port and R maintainer until 2009)
# Repository: CRAN
# Date/Publication: 2018-07-13 07:50:04 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
