travis:
  secure:
    BINSTAR_TOKEN: jNbyScl58SaEy9N/RZKiG+tRXx4SOinPyjZ+P95P9U5lQrneIYIsFm81900fLAz2KTpnRYMOqNHmVZcYHKZrZC9NxzDFMzeQSy8ln2lgkdV/7kDkCONR4wSxxN6Ki3Rv/kFsYDWf+4YalAiyZZe1zuLK5XHbQ+DLr0uHPJ+RUaU4VYPw6831ObSfuuU2BE6vgcTk3yZBRiyIIs6ifg3XN3v92Nd7vGX8/wupvEbtC7BcOvdcaMAlvHgzIAdUlGF/U5b1Ma/LB+hX4f3zU2btnPDi3TGCpIHmiWXNZUYeOALm1eMjp7BtddHWXiBSKXCQE4SOzneAKFcD2Kf9ZoW8m6OWoNqWtqNu3etxPv6Ap88CT5IDE5jQzuwt6lTl5V8LWlWQsgWAvhb7PKKCzXK19vvq8QmTRJo9vAfFwX8ngroVJNgBX3HY4YFIOYXUz+1xbFeAa867+Oc2RFJmdwYI3U0iy7N4Rhb3JmThTxXMqQFqagO51t2N1NznwUHXR5BzUaRkxTt6fkI+YMTDz5VwiK5RWnud2sUvYBkhgBeUX2zp/qPlXetyeZ9OoxFXpTKMDm9rBR2HHQo5becA7uEb/mC89aq1TjMpNheF0c16Ef5HpPJd9H+OBkrhGn+07jIn8O8XQ6OnLSoL+jXbDbkYmtgXt+8mUK/s+P+TII5eWHU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
