travis:
  secure:
    BINSTAR_TOKEN: Sf2ncC1Tf/Tuy7yPuBdXHaF+Z0+j4nvCL9pPNbq80rREW2eeEE3qpuigTOZpUnBy0SjGxe2IjKEndaCou0p3TOHGgTS/aWjXL2WzQbtecNHag0I8dW/Zf4OkA+cVzZHsjd3mfRNW+HKsu1tUCwvIIphq2+pqHjHQlm3mGpVTD+9cPcGeLc8OO6wigVnc/MTcSc2/zZsxTnu/+u/dzxZJgvKh6YPpAC/sWiwrzaOSruo5fGHLqr/rxWIrZ0g5SUOdPiUsUgTdBbKciPEHtelp+bK/UUzsh26QUpnYIzfKOVXQDfq8Im4MMZFFZdZGN2+JZqPDCDbGCQJGV+JZBaUI5VfJj2OJllunoyZ71DtEg2qUjbsuGfP++TkdS6aHo1HXOVijjpddcc7kXfGkz8Cz4zYEKX+ewq9xXJYRdy/cPxDI61WVss8wcSCqVmpXDQhHeLWy8C//wG5APuQfgj+j/uP3egkeP4gImak1GD9mPcZ8i/l7B6ba9vtnG0r/QK79dB2Gx2rQzI0Zlzi/qr9zQz4RShvuvt2pokM37MMAKJ1InxHEdJ8oDEA8bSGtsFe0jTAqUlbrkP0NUl3/5Qvg5X2YLfoxulkpEp+n8028c7BKLh2w0FtcwmvV/RtFIIVWOGfJfwO89LHmsHb89fJJ7lhrT1rbNMT+ySP1yXcfYew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
